require("vim._core.ui2").enable({ msg = { targets = "msg" } })

require("igorlfs.globals")
require("igorlfs.options")
require("igorlfs.keymaps")
require("igorlfs.autocmds")
require("igorlfs.filetype")
require("igorlfs.diagnostics")
require("igorlfs.env")
require("igorlfs.lsp")
require("igorlfs.watch")
require("ui.statusline")
require("ui.statuscolumn")
require("ui.tabline")
