require("vim._core.ui2").enable({})

require("igorlfs.globals")
require("igorlfs.options")
require("keymaps")
require("autocmds")
require("filetype")
require("igorlfs.diagnostics")
require("igorlfs.env")
require("igorlfs.lsp")
require("igorlfs.watch")
require("ui.statusline")
require("ui.statuscolumn")
require("ui.tabline")
